### ISSUE TITLE
Invalid nonce for: initiate-migration

### ISSUE THREAD

**Issue by bloszewski** [deliciousbrains/wp-migrate-db#77]
Hi. While trying to export database I receive such error:
`Migration failed
Invalid nonce for: initiate-migration`
Wordpress 4.7.5
Plugin 1.0

**Comment by pappu687** [comment]
Any update on this ?

**Comment by aaemnnosttv** [comment]
This usually happens when your WP login session has expired. Try refreshing the page, and try again.

**Comment by pappu687** [comment]
Not exactly, I had to downgrade again to 0.9.2 to get it fixed. 1.0 has this problem.

**Comment by bloszewski** [comment]
is this actually fixed? for me worked only the same "solution" as for @pappu687 - downgrading.
1.0 didn't work on any wordpress and any server I have tested it.

**Comment by mattgrshaw** [comment]
We did release a fix for some invalid nonce errors (caused by a combination of compatibility mode and some other plugins modifying the nonces) in WP Migrate DB version 1.0.2.

**Comment by bloszewski** [comment]
great. txt

**Comment by jajouka79** [comment]
im still getting this error with wp 4.9.6 and wp migrate pro 1.8.1 .

i have tried logging out and in again,

no difference

**Comment by jajouka79** [comment]
i fixed this using the terminal command :+1: 
wp migratedb setting update license 37ef0172-800e-4a9b-be31-7c29e12c30ed

but when trying to connect to another site i now get this error message :

Invalid nonce for: verify-connection-to-remote-site

**Comment by JRGould** [comment]
Hi @jajouka79 We don't provide support via GitHub, can you please email us about this issue so that we can help you look into it? 

You may also note that I have edited your previous comment so that your license key is not visible on this public forum.

**Comment by Josephthecodeacrhitect** [comment]
Just wanted to point out that I can still see @jajouka79 license key when I review edits @JRGould  I actually would have never noticed if you had not said something  about it

@jajouka79  Please remove your comment entirely to prevent anyone using your license key as im sure you  probably have had various users already obtain and use it since this is from a while back
